name: Build and Test

on:
  push:
    branches: [ main, develop, 'cursor/**' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

env:
  DOTNET_VERSION: '8.0.x'
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build:
    runs-on: windows-2022  # Use Windows Server 2022 explicitly to avoid migration notice
    timeout-minutes: 30
    strategy:
      matrix:
        configuration: [Debug, Release]
      fail-fast: false  # Don't cancel other jobs if one fails
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: System information
      run: |
        echo "=== System Information ==="
        echo "Available disk space:"
        Get-WmiObject -Class Win32_LogicalDisk | Where-Object DriveType -eq 3 | Format-Table DeviceID, @{Name="Size(GB)";Expression={[math]::Round($_.Size/1GB,2)}}, @{Name="FreeSpace(GB)";Expression={[math]::Round($_.FreeSpace/1GB,2)}}
        echo "Memory info:"
        $memory = Get-WmiObject -Class Win32_ComputerSystem
        echo "Total Physical Memory: $([math]::Round($memory.TotalPhysicalMemory/1GB,2)) GB"
        echo "Network connectivity test:"
        Test-NetConnection api.nuget.org -Port 443 -InformationLevel Detailed
        echo "PowerShell version:"
        $PSVersionTable.PSVersion
        echo "=== End System Information ==="
      shell: pwsh
      continue-on-error: true
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.nuget/packages
          %USERPROFILE%\.nuget\packages
          ${{ github.workspace }}/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/packages.lock.json', '**/Directory.Build.props') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
          
    - name: Clear NuGet cache (if needed)
      run: dotnet nuget locals all --clear
      continue-on-error: true
          
    - name: Restore dependencies
      id: restore
      run: |
        echo "Starting package restore..."
        dotnet restore MedicalLabAnalyzer.sln --verbosity normal --runtime win-x64 --disable-parallel:false
        echo "Package restore completed successfully"
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        DOTNET_NOLOGO: 1
        
    - name: Restore dependencies with diagnostics (retry on failure)
      if: failure() && steps.restore.outcome == 'failure'
      run: |
        echo "First restore attempt failed, retrying with diagnostic verbosity..."
        dotnet nuget locals all --clear
        dotnet clean MedicalLabAnalyzer.sln --verbosity minimal
        dotnet restore MedicalLabAnalyzer.sln --verbosity diagnostic --runtime win-x64 --force --no-cache
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        DOTNET_NOLOGO: 1
        
    - name: Validate restore success
      run: |
        echo "Validating package restore..."
        if (Test-Path "src/MedicalLabAnalyzer/obj/project.assets.json") {
          echo "✅ Main project assets restored successfully"
        } else {
          echo "❌ Main project assets missing"
          exit 1
        }
        if (Test-Path "tests/MedicalLabAnalyzer.Tests/obj/project.assets.json") {
          echo "✅ Test project assets restored successfully"
        } else {
          echo "❌ Test project assets missing"
          exit 1
        }
        echo "Package validation completed"
      shell: pwsh
        
    - name: Generate package lock files if missing
      run: |
        Write-Host "Checking for package lock files..."
        $lockFiles = Get-ChildItem -Recurse -Name "packages.lock.json"
        if ($lockFiles.Count -eq 0) {
          Write-Host "No lock files found. Generating lock files..."
          dotnet restore MedicalLabAnalyzer.sln --force-evaluate
          Write-Host "Lock files generated:"
          Get-ChildItem -Recurse -Name "packages.lock.json" | ForEach-Object { Write-Host "  $_" }
        } else {
          Write-Host "Lock files already exist:"
          $lockFiles | ForEach-Object { Write-Host "  $_" }
        }
      shell: pwsh
      
    - name: Build solution
      run: |
        echo "Building solution with configuration: ${{ matrix.configuration }}"
        dotnet build MedicalLabAnalyzer.sln --configuration ${{ matrix.configuration }} --no-restore --runtime win-x64 --verbosity normal
        echo "Build completed with exit code: $LASTEXITCODE"
      shell: pwsh
      
    - name: Diagnose build issues on failure
      if: failure()
      run: |
        Write-Host "=== Build Failed - Diagnostic Information ==="
        Write-Host "Checking for common build issues..."
        
        # Check if solution file exists
        if (Test-Path "MedicalLabAnalyzer.sln") {
          Write-Host "✓ Solution file found"
        } else {
          Write-Host "✗ Solution file not found"
        }
        
        # Check project files
        Get-ChildItem -Recurse -Filter "*.csproj" | ForEach-Object {
          Write-Host "Found project: $($_.FullName)"
        }
        
        # Check for missing packages
        Write-Host "Checking NuGet packages..."
        dotnet restore MedicalLabAnalyzer.sln --verbosity diagnostic | Select-String -Pattern "error|warning|failed" | ForEach-Object { Write-Host $_ }
        
        # Check target framework
        Write-Host "Checking target frameworks..."
        Get-Content "src/MedicalLabAnalyzer/MedicalLabAnalyzer.csproj" | Select-String -Pattern "TargetFramework"
      shell: pwsh
      
    - name: Create test results directory
      run: |
        Write-Host "Creating TestResults directory..."
        New-Item -ItemType Directory -Path "TestResults" -Force
        Write-Host "TestResults directory created: $(Test-Path 'TestResults')"
      shell: pwsh
      
    - name: Run tests
      run: |
        echo "Running tests for configuration: ${{ matrix.configuration }}"
        dotnet test MedicalLabAnalyzer.sln --configuration ${{ matrix.configuration }} --no-build --verbosity normal --logger trx --results-directory TestResults --collect:"XPlat Code Coverage"
        echo "Tests completed. Checking for test result files..."
        Get-ChildItem -Path TestResults -Recurse | ForEach-Object { Write-Host $_.FullName }
      shell: pwsh
      continue-on-error: true
      
    - name: Upload build artifacts (Release only)
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v4
      with:
        name: medical-lab-analyzer-release-${{ github.sha }}
        path: |
          src/MedicalLabAnalyzer/bin/Release/
        retention-days: 30
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      continue-on-error: true
      with:
        name: test-results-${{ matrix.configuration }}-${{ github.sha }}
        path: |
          TestResults/**/*.trx
          TestResults/**/*.xml
          TestResults/**/*.coverage
        retention-days: 7
        if-no-files-found: ignore
        
    - name: Upload diagnostic logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      continue-on-error: true
      with:
        name: diagnostic-logs-${{ matrix.configuration }}-${{ github.sha }}
        path: |
          **/*.binlog
          **/*.log
          **/obj/project.assets.json
        retention-days: 7
        if-no-files-found: ignore