name: Simple Test - MedicalLabAnalyzer

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.100'
  SOLUTION_FILE: 'MedicalLabAnalyzer.sln'

jobs:
  simple-test:
    name: Simple Build and Test
    runs-on: windows-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: List repository contents
      run: |
        Write-Host "=== Repository Contents ==="
        Get-ChildItem -Name
        Write-Host "=== Solution Files ==="
        Get-ChildItem -Name "*.sln"

    - name: Clear NuGet cache
      run: |
        Write-Host "=== Clearing NuGet Cache ==="
        dotnet nuget locals all --clear
        Write-Host "✅ NuGet cache cleared"

    - name: Restore packages
      run: |
        Write-Host "=== Restoring Packages ==="
        dotnet restore "${{ env.SOLUTION_FILE }}" --verbosity normal
        if ($LASTEXITCODE -eq 0) {
          Write-Host "✅ Packages restored successfully"
        } else {
          Write-Host "❌ Package restore failed"
          exit 1
        }

    - name: Build solution
      run: |
        Write-Host "=== Building Solution ==="
        dotnet build "${{ env.SOLUTION_FILE }}" --configuration Release --no-restore --verbosity normal
        if ($LASTEXITCODE -eq 0) {
          Write-Host "✅ Solution built successfully"
        } else {
          Write-Host "❌ Build failed"
          exit 1
        }

    - name: Create TestResults directory
      run: |
        Write-Host "=== Creating TestResults Directory ==="
        New-Item -ItemType Directory -Path "TestResults" -Force
        Write-Host "✅ TestResults directory created"

    - name: Run tests
      run: |
        Write-Host "=== Running Tests ==="
        dotnet test "${{ env.SOLUTION_FILE }}" --configuration Release --no-build --verbosity normal --logger "console;verbosity=normal" --results-directory ./TestResults
        if ($LASTEXITCODE -eq 0) {
          Write-Host "✅ Tests completed successfully"
        } else {
          Write-Host "❌ Tests failed"
          exit 1
        }

    - name: Check test results
      run: |
        Write-Host "=== Checking Test Results ==="
        $testResults = Get-ChildItem -Path "TestResults/*.trx" -ErrorAction SilentlyContinue
        if ($testResults) {
          Write-Host "✅ Test results found:"
          $testResults | ForEach-Object { Write-Host "  - $($_.Name)" }
        } else {
          Write-Host "⚠️ No test result files found"
        }

    - name: Check build artifacts
      run: |
        Write-Host "=== Checking Build Artifacts ==="
        $binPath = "bin/Release/net8.0-windows"
        if (Test-Path $binPath) {
          $files = Get-ChildItem $binPath -Recurse -File | Measure-Object -Property Length -Sum
          Write-Host "✅ Build artifacts found: $($files.Count) files, $([math]::Round($files.Sum / 1MB, 2)) MB"
        } else {
          Write-Host "⚠️ No build artifacts found in $binPath"
          # Check other possible paths
          $possiblePaths = @("bin/Release", "bin", "obj/Release")
          foreach ($path in $possiblePaths) {
            if (Test-Path $path) {
              Write-Host "Found files in: $path"
              Get-ChildItem $path -Recurse -File | Select-Object -First 5 | ForEach-Object { Write-Host "  - $($_.Name)" }
            }
          }
        }

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: SimpleTestResults-${{ github.run_number }}
        path: TestResults/
        retention-days: 30

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SimpleBuildArtifacts-${{ github.run_number }}
        path: |
          bin/Release/net8.0-windows/
          obj/Release/net8.0-windows/
        retention-days: 30

    - name: Success summary
      run: |
        Write-Host "✅ Simple test completed successfully!"
        Write-Host "Build Number: ${{ github.run_number }}"
        Write-Host "Commit: ${{ github.sha }}"
        Write-Host "Branch: ${{ github.ref_name }}"
        Write-Host "Workflow: ${{ github.workflow }}"